---
- hosts: localhost
  become: yes
  tasks:
    - ec2:
        image: "ami-033a1ebf088e56e81"
        instance type: "t2.micro"
        region: "us-east-1"
        wait: yes
        count: 1
        state: "present"
        vpc_subnet_id: "{{ pubsubnet_result.subnet.id }}"
        assign_public_ip: yes
        group_id: "{{ security_group_results.group_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_tags:
          Name: "spk"
