--
- hosts: localhost
  become: yes
  tasks:
    - ec2_vpc_subnet:       
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: "us-east-1"
        az: "us-east-1b"
        state: "present"
        cidr: "10.0.16.0/20"
        map_public: no
        resource_tags:
          Name: "spk-pvt"
      register: pvtsubnet_result
